[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.7.0"

[[constraint]]
  name = "github.com/go-contrib/uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
